echo "Welcome to Paypal"                 
echo "Paypal your payment gateway"        
echo "Paypal is the gateway of the future" 
echo "Paypal is offering 30% discount"    
echo "Good deals for returing clients"
echo "I am handsome"
echo "the day is fine"
